#!/usr/bin/env bash
set -e;


if [ -n "${POSTGRES_NON_ROOT_USER:-}" ] && [ -n "${POSTGRES_NON_ROOT_PASSWORD:-}" ]; then
	psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${POSTGRES_NON_ROOT_USER} WITH PASSWORD '${POSTGRES_NON_ROOT_PASSWORD}';
    CREATE DATABASE ${N8N_POSTGRES_DB};
    CREATE DATABASE ${BASEROW_POSTGRES_DB};
    GRANT ALL PRIVILEGES ON DATABASE ${N8N_POSTGRES_DB} TO ${POSTGRES_NON_ROOT_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${BASEROW_POSTGRES_DB} TO ${POSTGRES_NON_ROOT_USER};
	EOSQL

	psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "${N8N_POSTGRES_DB}" -c "GRANT ALL ON SCHEMA public TO ${POSTGRES_NON_ROOT_USER};"
	psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "${BASEROW_POSTGRES_DB}" -c "GRANT ALL ON SCHEMA public TO ${POSTGRES_NON_ROOT_USER};"
else
	echo "SETUP INFO: No Environment variables given!"
fi
